const data = [
    {
        "apiCode": "CCCC-0036",
        "apiName1": "开庭公告",
        "apiName2": "开庭公告",
        "apiCategory": "法律诉讼",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/jr/ktannouncement/2.0",
        "description": "可以通过公司名称或ID获取企业开庭公告，开庭公告信息包括被告/被上诉人、法院、原告/上诉人、开庭日期、案由、内部ID、案号等字段的详细信息",
        "price": 0.017,
        "totalCalls": 335258,
        "validCalls": 300833,
        "totalCost": 4993.83,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "法律诉讼",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0032",
        "apiName1": "法院公告",
        "apiName2": "法院公告",
        "apiCategory": "法律诉讼",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/jr/courtAnnouncement/2.0",
        "description": "可以通过公司名称或ID获取企业法院公告，法院公告信息包括执行法院、案件内容、公告类型、刊登日期、公司名、当事人等字段的详细信息",
        "price": 0.017,
        "totalCalls": 249916,
        "validCalls": 203218,
        "totalCost": 3373.42,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "法律诉讼",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0111",
        "apiName1": "裁判文书",
        "apiName2": "裁判文书核查-裁判文书核查",
        "apiCategory": "法律诉讼",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/action/legal/judgmentDocCheck/getList",
        "description": "裁判文书核查-裁判文书核查",
        "price": 0.3,
        "totalCalls": 7,
        "validCalls": 7,
        "totalCost": 2.1,
        "supplierApi": "裁判文书核查",
        "remark": "/yj/JudgmentDocCheck/GetList",
        "tags": [
            "法律诉讼",
            "企查查",
            "POST",
            "未改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0112",
        "apiName1": "裁判文书",
        "apiName2": "裁判文书核查-裁判文书详情",
        "apiCategory": "法律诉讼",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/action/legal/judgmentDocCheck/getDetail",
        "description": "裁判文书核查-裁判文书详情",
        "price": 0.3,
        "totalCalls": 7,
        "validCalls": 7,
        "totalCost": 2.1,
        "supplierApi": "裁判文书核查",
        "remark": "/yj/JudgmentDocCheck/GetDetail",
        "tags": [
            "法律诉讼",
            "企查查",
            "POST",
            "未改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0110",
        "apiName1": "法院公告",
        "apiName2": "法院公告核查-公告详情",
        "apiCategory": "法律诉讼",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/action/legal/courtNoticeCheck/getDetail",
        "description": "法院公告核查-公告详情",
        "price": 0.5,
        "totalCalls": 4,
        "validCalls": 4,
        "totalCost": 2,
        "supplierApi": "法院公告核查",
        "remark": "/yj/CourtNoticeCheck/GetDetail",
        "tags": [
            "法律诉讼",
            "企查查",
            "POST",
            "未改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0117",
        "apiName1": "法院公告",
        "apiName2": "法院公告核查-公告列表",
        "apiCategory": "法律诉讼",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/action/legal/courtNoticeCheck/getList",
        "description": "法院公告核查-公告列表",
        "price": 0.5,
        "totalCalls": 1,
        "validCalls": 1,
        "totalCost": 0.5,
        "supplierApi": "法院公告核查",
        "remark": "/yj/CourtNoticeCheck/GetList",
        "tags": [
            "法律诉讼",
            "企查查",
            "POST",
            "未改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0113",
        "apiName1": "开庭公告",
        "apiName2": "开庭公告核查-开庭公告核查",
        "apiCategory": "法律诉讼",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/action/legal/courtAnnoCheck/getList",
        "description": "开庭公告核查-开庭公告核查",
        "price": 0.5,
        "totalCalls": 1,
        "validCalls": 1,
        "totalCost": 0.5,
        "supplierApi": "开庭公告核查",
        "remark": "/yj/CourtAnnoCheck/GetList",
        "tags": [
            "法律诉讼",
            "企查查",
            "POST",
            "未改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0114",
        "apiName1": "开庭公告",
        "apiName2": "开庭公告核查-开庭公告详情",
        "apiCategory": "法律诉讼",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/action/legal/courtAnnoCheck/getDetail",
        "description": "开庭公告核查-开庭公告详情",
        "price": 0.5,
        "totalCalls": 1,
        "validCalls": 1,
        "totalCost": 0.5,
        "supplierApi": "开庭公告核查",
        "remark": "/yj/CourtAnnoCheck/GetDetail",
        "tags": [
            "法律诉讼",
            "企查查",
            "POST",
            "未改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0115",
        "apiName1": "立案信息",
        "apiName2": "立案信息核查-立案信息核查",
        "apiCategory": "法律诉讼",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/action/legal/caseFilingCheck/getList",
        "description": "立案信息核查-立案信息核查",
        "price": 0.5,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "立案信息核查",
        "remark": "/yj/CaseFilingCheck/GetList",
        "tags": [
            "法律诉讼",
            "企查查",
            "POST",
            "未改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0116",
        "apiName1": "立案信息",
        "apiName2": "立案信息核查-立案信息详情",
        "apiCategory": "法律诉讼",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/action/legal/caseFilingCheck/getDetail",
        "description": "立案信息核查-立案信息详情",
        "price": 0.5,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "立案信息核查",
        "remark": "/yj/CaseFilingCheck/GetDetail",
        "tags": [
            "法律诉讼",
            "企查查",
            "POST",
            "未改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0033",
        "apiName1": "失信人",
        "apiName2": "失信人",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/jr/dishonest/2.0",
        "description": "可以通过公司名称或ID判定企业失信情况，失信信息包括失信人名称、组织机构代码、履行情况、失信行为具体情形等字段的详细信息",
        "price": 0.017,
        "totalCalls": 2021546,
        "validCalls": 1201770,
        "totalCost": 19949.38,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "风险识别",
            "天眼查",
            "GET",
            "已改造",
            "低价",
            "热门",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0017",
        "apiName1": "行政处罚",
        "apiName2": "行政处罚-工商局",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/punishmentInfo/bureau",
        "description": "可以通过公司名称或ID获取企业行政处罚信息，行政处罚信息包括处罚日期、决定书文号、处罚事由/违法行为类型、处罚结果/内容、处罚单位、数据来源等信息",
        "price": 0.017,
        "totalCalls": 1854170,
        "validCalls": 1143798,
        "totalCost": 18987.05,
        "supplierApi": "",
        "remark": "/services/open/hi/punishmentInfo/3.0",
        "tags": [
            "风险识别",
            "天眼查",
            "GET",
            "已改造",
            "低价",
            "热门",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0012",
        "apiName1": "被执行人",
        "apiName2": "被执行人核查",
        "apiCategory": "风险识别",
        "provider": "企查查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/supplier/risk/person/subjected/GetList",
        "description": "核查企业是否存在被执行情况，助力风险管控。返回包括但不限于案号、立案信息、关联对象、执行法院、执行标的等信息。",
        "price": 0.3,
        "totalCalls": 134624,
        "validCalls": 130592,
        "totalCost": 39177.6,
        "supplierApi": "被执行人核查",
        "remark": "https://pro.qcc.com/api/yj/ZhixingCheck/GetList",
        "tags": [
            "风险识别",
            "企查查",
            "GET",
            "已改造",
            "中价",
            "常用",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0126",
        "apiName1": "被执行人",
        "apiName2": "被执行人核查-PostRequest",
        "apiCategory": "风险识别",
        "provider": "企查查",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/qfc/supplier/risk/person/subjected/GetList",
        "description": "核查企业是否存在被执行情况，助力风险管控。返回包括但不限于案号、立案信息、关联对象、执行法院、执行标的等信息。",
        "price": 0.3,
        "totalCalls": 64,
        "validCalls": 64,
        "totalCost": 19.2,
        "supplierApi": "被执行人核查",
        "remark": "https://pro.qcc.com/api/yj/ZhixingCheck/GetList",
        "tags": [
            "风险识别",
            "企查查",
            "POST",
            "已改造",
            "中价",
            "Post接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0034",
        "apiName1": "被执行人",
        "apiName2": "被执行人",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/jr/zhixinginfo/2.0",
        "description": "可以通过公司名称或ID获取被执行人信息，被执行人信息包括执行法院、案件内容、执行标的、被执行人名称、组织机构代码等字段的详细信息",
        "price": 0.017,
        "totalCalls": 382096,
        "validCalls": 304152,
        "totalCost": 5048.92,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "风险识别",
            "天眼查",
            "GET",
            "已改造",
            "低价",
            "常用",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0016",
        "apiName1": "行政处罚",
        "apiName2": "历史行政处罚",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/punishmentInfo/3.0",
        "description": "可以通过公司名称或ID获取企业历史行政处罚信息，历史行政处罚信息包括处罚日期、决定书文号、处罚事由/违法行为类型、处罚结果/内容、处罚单位、数据来源等信息",
        "price": 0.017,
        "totalCalls": 156934,
        "validCalls": 109327,
        "totalCost": 1814.83,
        "supplierApi": "",
        "remark": "/services/open/hi/punishmentInfo/3.0",
        "tags": [
            "风险识别",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0018",
        "apiName1": "行政处罚",
        "apiName2": "行政处罚-其他来源",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/punishmentInfo/other",
        "description": "可以通过公司名称或ID获取企业行政处罚信息，行政处罚信息包括处罚日期、决定书文号、处罚事由/违法行为类型、处罚结果/内容、处罚单位、数据来源等信息",
        "price": 0.017,
        "totalCalls": 145541,
        "validCalls": 98493,
        "totalCost": 1634.98,
        "supplierApi": "",
        "remark": "/services/open/hi/punishmentInfo/3.0",
        "tags": []
    },
    {
        "apiCode": "CCCC-0019",
        "apiName1": "股权出质",
        "apiName2": "股权出质",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/equityInfo/2.0",
        "description": "可以通过公司名称或ID获取股权出质信息，包括企业质权人信息、出质人信息、出质股权标的企业信息、出质股权数额等字段的详细信息",
        "price": 0.017,
        "totalCalls": 94658,
        "validCalls": 94647,
        "totalCost": 1571.14,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "风险识别",
            "天眼查",
            "GET",
            "已改造",
            "低价",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0021",
        "apiName1": "欠税公告",
        "apiName2": "欠税公告",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/ownTax/2.0",
        "description": "可以通过公司名称或ID获取企业欠税信息，企业欠税信息包括欠税公告、纳税人识别号、证件号码、经营地点、欠税税种、欠税余额等字段的详细信息",
        "price": 0.017,
        "totalCalls": 14303,
        "validCalls": 14222,
        "totalCost": 236.09,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "风险识别",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0011",
        "apiName1": "失信人",
        "apiName2": "失信查询",
        "apiCategory": "风险识别",
        "provider": "企查查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/supplier/risk/trust/inquiry/GetList",
        "description": "核查企业的是否存在失信被执行情况，助力风险管控。核查该企业的具体失信情况及履行情况，返回包括但不限于案号、立案信息、失信行为、执行法院、执行标的等信息。",
        "price": 0.3,
        "totalCalls": 52,
        "validCalls": 51,
        "totalCost": 15.3,
        "supplierApi": "失信核查",
        "remark": "https://pro.qcc.com/api/yj/ShixinCheck/GetList",
        "tags": [
            "风险识别",
            "企查查",
            "GET",
            "已改造",
            "中价",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0125",
        "apiName1": "失信人",
        "apiName2": "失信查询-PostRequest",
        "apiCategory": "风险识别",
        "provider": "企查查",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/qfc/supplier/risk/trust/inquiry/GetList",
        "description": "核查企业的是否存在失信被执行情况，助力风险管控。核查该企业的具体失信情况及履行情况，返回包括但不限于案号、立案信息、失信行为、执行法院、执行标的等信息。",
        "price": 0.3,
        "totalCalls": 47,
        "validCalls": 47,
        "totalCost": 14.1,
        "supplierApi": "失信核查",
        "remark": "https://pro.qcc.com/api/yj/ShixinCheck/GetList",
        "tags": []
    },
    {
        "apiCode": "CCCC-0013",
        "apiName1": "限制高消费",
        "apiName2": "限制高消费核查",
        "apiCategory": "风险识别",
        "provider": "企查查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/supplier/risk/high/consumption/GetList",
        "description": "核查企业是否存在被执行情况，助力风险管控。返回包括但不限于案号、立案信息、关联对象、执行法院、执行标的等信息。",
        "price": 0.5,
        "totalCalls": 13601,
        "validCalls": 13573,
        "totalCost": 6786.5,
        "supplierApi": "限制高消费核查",
        "remark": "https://pro.qcc.com/api/yj/SumptuaryCheck/GetList",
        "tags": [
            "风险识别",
            "企查查",
            "GET",
            "已改造",
            "中价",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0127",
        "apiName1": "限制高消费",
        "apiName2": "限制高消费核查-PostRequest",
        "apiCategory": "风险识别",
        "provider": "企查查",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/qfc/supplier/risk/high/consumption/GetList",
        "description": "核查企业是否存在被执行情况，助力风险管控。返回包括但不限于案号、立案信息、关联对象、执行法院、执行标的等信息。",
        "price": 0.5,
        "totalCalls": 93,
        "validCalls": 93,
        "totalCost": 46.5,
        "supplierApi": "限制高消费核查",
        "remark": "https://pro.qcc.com/api/yj/SumptuaryCheck/GetList",
        "tags": []
    },
    {
        "apiCode": "CCCC-0038",
        "apiName1": "股权穿透",
        "apiName2": "股权穿透图",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/investtree/v3",
        "description": "可以通过公司ID获取企业上下游对外投资关系，包含直接与间接投资企业等",
        "price": 0.017,
        "totalCalls": 227393,
        "validCalls": 227157,
        "totalCost": 3770.81,
        "supplierApi": "",
        "remark": "/services/v3/open/investtree",
        "tags": [
            "工商信息",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口",
            "工商",
            "关系图谱"
        ]
    },
    {
        "apiCode": "CCCC-0039",
        "apiName1": "实际控制人",
        "apiName2": "疑似实际控制人",
        "apiCategory": "工商信息",
        "provider": "自有接口",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/actualControl/3.0",
        "description": "可以通过公司名称或ID获取股权向上穿透后识别的企业疑似实际控制人，包含（一名或多名）疑似控制人姓名、层级关系等字段信息",
        "price": 0,
        "totalCalls": 159316,
        "validCalls": 159240,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "企查查接口地址，但实际为落库数据",
        "tags": [
            "工商信息",
            "自有接口",
            "GET",
            "已改造",
            "免费",
            "常用",
            "Get接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0024",
        "apiName1": "分支机构",
        "apiName2": "分支机构",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/branch/2.0",
        "description": "可以通过公司名称或ID获取企业分支机构信息，分支机构信息包括分公司名称或ID、企业法人、经营状态、分公司总数等字段的详细信息",
        "price": 0.017,
        "totalCalls": 143455,
        "validCalls": 143334,
        "totalCost": 2379.34,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "工商信息",
            "天眼查",
            "GET",
            "已改造",
            "低价",
            "常用",
            "Get接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0027",
        "apiName1": "对外投资",
        "apiName2": "对外投资",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/inverst/2.0",
        "description": "可以通过公司名称或ID获取企业对外投资信息，对外投资信息包括被投资企业、企业法人、投资占比、对外投资总数等字段的详细信息",
        "price": 0.017,
        "totalCalls": 141723,
        "validCalls": 141715,
        "totalCost": 2352.47,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "工商信息",
            "天眼查",
            "GET",
            "已改造",
            "低价",
            "常用",
            "Get接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0118",
        "apiName1": "分支机构",
        "apiName2": "通过公司名获取企业分支机构信息",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/commercial/business/getECIBranchList",
        "description": "可以通过公司名称或ID获取企业分支机构信息",
        "price": 0.5,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "分支机构",
        "remark": "/yj/ECIBranch/GetList",
        "tags": []
    },
    {
        "apiCode": "CCCC-0119",
        "apiName1": "股权穿透",
        "apiName2": "股权穿透(四层)",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/commercial/business/getEquityThrough",
        "description": "股权穿透(四层)",
        "price": 3,
        "totalCalls": 1098,
        "validCalls": 1098,
        "totalCost": 3294,
        "supplierApi": "股权穿透(四层)",
        "remark": "/yj/EquityThrough/GetEquityThrough",
        "tags": [
            "工商信息",
            "企查查",
            "POST",
            "未改造",
            "高价",
            "Post接口",
            "工商",
            "关系图谱"
        ]
    },
    {
        "apiCode": "CCCC-0025",
        "apiName1": "主要人员",
        "apiName2": "主要人员",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/staff/2.0",
        "description": "可以通过公司名称或ID获取企业主要人员信息，主要人员信息包括董事、监事、高级管理人员姓名、职位、主要人员总数等字段的详细信息",
        "price": 0.017,
        "totalCalls": 52418,
        "validCalls": 52009,
        "totalCost": 863.35,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "工商信息",
            "天眼查",
            "GET",
            "已改造",
            "低价",
            "Get接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0128",
        "apiName1": "股权穿透",
        "apiName2": "股权穿透图-已方数据源",
        "apiCategory": "工商信息",
        "provider": "自有接口",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/company/model/investtree",
        "description": "股权穿透图-已方数据源",
        "price": 0,
        "totalCalls": 26293,
        "validCalls": 26293,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0137",
        "apiName1": "股权关系挖掘",
        "apiName2": "判断两个企业是否具有股权关系",
        "apiCategory": "关联族谱",
        "provider": "自有接口",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/actual/control/equity/relationship",
        "description": "判断两个企业是否具有股权关系,如果企业信息有误返回没有关系",
        "price": 0,
        "totalCalls": 1318842,
        "validCalls": 1317098,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "实控人",
        "tags": [
            "关联族谱",
            "自有接口",
            "POST",
            "已改造",
            "免费",
            "热门",
            "Post接口",
            "关系图谱"
        ]
    },
    {
        "apiCode": "CCCC-0008",
        "apiName1": "股权关系揭示接口",
        "apiName2": "关系族谱-股权关系揭示",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/relationship/warning/equity",
        "description": "根据公司名称、关联类型(股权关联、投资关联)、股权比例等参数来揭示公司之间的股权及其投资关系",
        "price": 1.2,
        "totalCalls": 1248933,
        "validCalls": 1093950,
        "totalCost": 1312740,
        "supplierApi": "股权关系揭示接口",
        "remark": "/api/company/findRelation",
        "tags": [
            "关联族谱",
            "企查查",
            "GET",
            "未改造",
            "高价",
            "热门",
            "Get接口",
            "关系图谱"
        ]
    },
    {
        "apiCode": "CCCC-0122",
        "apiName1": "股权关系揭示接口",
        "apiName2": "关系族谱-股权关系揭示-PostRequest",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/qfc/relationship/warning/equity",
        "description": "根据公司名称、关联类型(股权关联、投资关联)、股权比例等参数来揭示公司之间的股权及其投资关系",
        "price": 1.2,
        "totalCalls": 3157,
        "validCalls": 1596,
        "totalCost": 1915.2,
        "supplierApi": "股权关系揭示接口",
        "remark": "/api/company/findRelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0082",
        "apiName1": "股权关系揭示接口",
        "apiName2": "股权关系揭示",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/depth/relationship/findRelation",
        "description": "股权关系揭示",
        "price": 1.2,
        "totalCalls": 52,
        "validCalls": 52,
        "totalCost": 62.4,
        "supplierApi": "股权关系揭示接口",
        "remark": "/company/findRelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0007",
        "apiName1": "关联关系挖掘接口",
        "apiName2": "关联关系挖掘-联系方式揭示",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/relationship/warning/contactWay",
        "description": "根据公司名称，关联类型等参数来挖掘企业之间董监高自然人、联系方式、组合关联(人企、股权、历史投资任职)的关联关系",
        "price": 1.2,
        "totalCalls": 396820,
        "validCalls": 260503,
        "totalCost": 312603.6,
        "supplierApi": "关联关系挖掘接口",
        "remark": "/api/corp/correlation/findCorrelation",
        "tags": [
            "关联族谱",
            "企查查",
            "GET",
            "未改造",
            "高价",
            "常用",
            "Get接口",
            "关系图谱"
        ]
    },
    {
        "apiCode": "CCCC-0010",
        "apiName1": "关联关系挖掘接口",
        "apiName2": "关联关系挖掘-人物关系揭示",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/relationship/warning/character",
        "description": "根据公司名称，关联类型等参数来挖掘企业之间董监高自然人、联系方式、组合关联(人企、股权、历史投资任职)的关联关系",
        "price": 1.2,
        "totalCalls": 129294,
        "validCalls": 96540,
        "totalCost": 115848,
        "supplierApi": "关联关系挖掘接口",
        "remark": "/api/corp/correlation/findCorrelation",
        "tags": [
            "关联族谱",
            "企查查",
            "GET",
            "未改造",
            "高价",
            "常用",
            "Get接口",
            "关系图谱"
        ]
    },
    {
        "apiCode": "CCCC-0124",
        "apiName1": "关联关系挖掘接口",
        "apiName2": "关联关系挖掘-人物关系揭示-PostRequest",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/qfc/relationship/warning/character",
        "description": "根据公司名称，关联类型等参数来挖掘企业之间董监高自然人、联系方式、组合关联(人企、股权、历史投资任职)的关联关系",
        "price": 1.2,
        "totalCalls": 6288,
        "validCalls": 5219,
        "totalCost": 6262.8,
        "supplierApi": "关联关系挖掘接口",
        "remark": "/api/corp/correlation/findCorrelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0121",
        "apiName1": "关联关系挖掘接口",
        "apiName2": "关联关系挖掘-联系方式揭示-PostRequest",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/qfc/relationship/warning/contactWay",
        "description": "根据公司名称，关联类型等参数来挖掘企业之间董监高自然人、联系方式、组合关联(人企、股权、历史投资任职)的关联关系",
        "price": 1.2,
        "totalCalls": 2122,
        "validCalls": 779,
        "totalCost": 934.8,
        "supplierApi": "关联关系挖掘接口",
        "remark": "/api/corp/correlation/findCorrelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0089",
        "apiName1": "关联关系挖掘接口",
        "apiName2": "关联关系挖掘",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/depth/relationship/findCorrelation",
        "description": "关联关系挖掘",
        "price": 1.2,
        "totalCalls": 26,
        "validCalls": 26,
        "totalCost": 31.2,
        "supplierApi": "关联关系挖掘接口",
        "remark": "/corp/correlation/findCorrelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0088",
        "apiName1": "合作关系挖掘接口",
        "apiName2": "合作关系挖掘",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/depth/relationship/findPartnershipRelation",
        "description": "合作关系挖掘",
        "price": 1.2,
        "totalCalls": 55,
        "validCalls": 55,
        "totalCost": 66,
        "supplierApi": "合作关系挖掘接口",
        "remark": "/corp/correlation/findPartnershipRelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0094",
        "apiName1": "深度关系挖掘",
        "apiName2": "深度关系挖掘-页面",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/plugin/supply/relationship",
        "description": "向供应链提供-深度关系挖掘-页面",
        "price": 0,
        "totalCalls": 213405,
        "validCalls": 213397,
        "totalCost": 0,
        "supplierApi": "嵌入页面",
        "remark": "/relationship/reveal-correlation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0084",
        "apiName1": "深度关系挖掘",
        "apiName2": "深度关系挖掘访问页面",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/depth/relationship/pluginLogin",
        "description": "深度关系挖掘访问页面",
        "price": 0,
        "totalCalls": 86,
        "validCalls": 86,
        "totalCost": 0,
        "supplierApi": "嵌入页面",
        "remark": "/modules/open/relationship",
        "tags": []
    },
    {
        "apiCode": "CCCC-0086",
        "apiName1": "司法关系挖掘接口",
        "apiName2": "司法关系挖掘",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/depth/relationship/findJudicialRelation",
        "description": "司法关系挖掘",
        "price": 1.2,
        "totalCalls": 50,
        "validCalls": 50,
        "totalCost": 60,
        "supplierApi": "司法关系挖掘接口",
        "remark": "/corp/correlation/findJudicialRelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0041",
        "apiName1": "上市公司企业简介",
        "apiName2": "上市公司企业简介",
        "apiCategory": "上市信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/stock/companyInfo/2.0",
        "description": "可以通过公司名称或ID获取上市公司企业简介，上市公司企业简介包括公司全称、曾用名、工商登记号、注册资本、所属行业、主要人员、控股股东、实际控制人、最终控制人、主营业务等",
        "price": 0.017,
        "totalCalls": 206717,
        "validCalls": 99797,
        "totalCost": 1656.63,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "上市信息",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口"
        ]
    },
    {
        "apiCode": "CCCC-0045",
        "apiName1": "新闻舆情",
        "apiName2": "新闻舆情",
        "apiCategory": "新闻舆情",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/appreciation/ps/news",
        "description": "根据公司id或公司名称（精确匹配）获取新闻列表",
        "price": 0.017,
        "totalCalls": 114002,
        "validCalls": 91182,
        "totalCost": 1513.62,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "新闻舆情",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口"
        ]
    },
    {
        "apiCode": "CCCC-0048",
        "apiName1": "专利查询",
        "apiName2": "专利详细信息",
        "apiCategory": "知识产权",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/academy/provider/eviv4/search/getDetails",
        "description": "专利详细信息",
        "price": 0.3,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "专利查询",
        "remark": "https://api.qichacha.com/CustomerPatentV4/GetDetails",
        "tags": []
    },
    {
        "apiCode": "CCCC-0049",
        "apiName1": "专利查询",
        "apiName2": "专利多重查询",
        "apiCategory": "知识产权",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/academy/provider/eviv4/search/patentSearch",
        "description": "专利多重查询",
        "price": 0.3,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "专利查询",
        "remark": "https://api.qichacha.com/CustomerPatentV4/Search",
        "tags": []
    },
    {
        "apiCode": "CCCC-0050",
        "apiName1": "专利查询",
        "apiName2": "公司专利多重查询",
        "apiCategory": "知识产权",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/academy/provider/eviv4/search/searchMultiPatents",
        "description": "公司专利多重查询",
        "price": 0.3,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "专利查询",
        "remark": "https://api.qichacha.com/CustomerPatentV4/SearchMultiPatents",
        "tags": []
    },
    {
        "apiCode": "CCCC-0005",
        "apiName1": "企业性质分析",
        "apiName2": "企业性质分析",
        "apiCategory": "工商信息",
        "provider": "自有接口",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/company/model/companyType",
        "description": "通过企业名称/统一社会信用代码，进行企业性质分析",
        "price": 0,
        "totalCalls": 6968265,
        "validCalls": 6948535,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "工商信息",
            "自有接口",
            "POST",
            "已改造",
            "免费",
            "热门",
            "Post接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0003",
        "apiName1": "企业基本信息",
        "apiName2": "工商基本信息查询",
        "apiCategory": "工商信息",
        "provider": "大司空",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/dsk/company/business/info",
        "description": "根据企业名称或企业统一社会信用代码查询企业工商基本信息",
        "price": 0,
        "totalCalls": 6023059,
        "validCalls": 5924902,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "工商信息",
            "大司空",
            "POST",
            "未改造",
            "免费",
            "热门",
            "Post接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0023",
        "apiName1": "企业基本信息",
        "apiName2": "企业基本信息（含企业联系方式）",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/baseinfo/normal",
        "description": "可以通过公司名称或ID或ID称获取企业基本信息和企业联系方式，包括公司名称或ID、类型、成立日期、电话、邮箱、网址等字段的详细信息",
        "price": 0.017,
        "totalCalls": 5231671,
        "validCalls": 5517665,
        "totalCost": 91593.24,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "工商信息",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "热门",
            "Get接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0004",
        "apiName1": "模糊搜索",
        "apiName2": "企业名称模糊搜索",
        "apiCategory": "工商信息",
        "provider": "大司空",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/dsk/company/fuzzy/search",
        "description": "通过企业id/企业名称/统一社会信用代码，查询该企业的工商基本信息，包括工商地址、登记机关、经营范围、参保人数等",
        "price": 0,
        "totalCalls": 2682381,
        "validCalls": 2670840,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "获取匹配企业列表，企业列表包括公司名称，企业信用代码",
        "tags": [
            "工商信息",
            "大司空",
            "POST",
            "未改造",
            "免费",
            "热门",
            "Post接口",
            "工商",
            "搜索"
        ]
    },
    {
        "apiCode": "CCCC-0043",
        "apiName1": "模糊搜索",
        "apiName2": "搜索",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/search/2.0",
        "description": "可以通过关键词获取企业列表，企业列表包括公司名称或ID、类型、成立日期、经营状态、统一社会信用代码等字段的详细信息",
        "price": 0.017,
        "totalCalls": 2107417,
        "validCalls": 2076687,
        "totalCost": 34473,
        "supplierApi": "",
        "remark": "获取企业列表，企业列表包括公司基本信息",
        "tags": [
            "工商信息",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "热门",
            "Get接口",
            "工商",
            "搜索"
        ]
    },
    {
        "apiCode": "CCCC-0014",
        "apiName1": "严重违法",
        "apiName2": "严重违法",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/illegalinfo/2.0",
        "description": "可以通过公司名称或ID获取企业严重违法信息，严重违法信息包括列入/移除原因、时间、做出决定机关等字段的详细信息",
        "price": 0.017,
        "totalCalls": 1716587,
        "validCalls": 1026982,
        "totalCost": 17047.9,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "风险识别",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "热门",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0006",
        "apiName1": "企业规模",
        "apiName2": "企业规模",
        "apiCategory": "工商信息",
        "provider": "自有接口",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/company/model/enterprise/scale",
        "description": "通过企业名称/统一社会信用代码，查询该企业的企业规模等",
        "price": 0,
        "totalCalls": 1382607,
        "validCalls": 1382512,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "工商信息",
            "自有接口",
            "POST",
            "已改造",
            "免费",
            "热门",
            "Post接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0028",
        "apiName1": "变更记录",
        "apiName2": "变更记录",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/changeinfo/2.0",
        "description": "可以通过公司名称或ID获取企业变更记录，变更记录包括工商变更事项、变更前后信息等字段的详细信息",
        "price": 0.017,
        "totalCalls": 491792,
        "validCalls": 491734,
        "totalCost": 8162.78,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "工商信息",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0035",
        "apiName1": "法律诉讼",
        "apiName2": "法律诉讼",
        "apiCategory": "法律诉讼",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/jr/lawSuit/3.0",
        "description": "可以通过公司名称或ID获取企业法律诉讼信息，包括案号、案件名称、案由、案件金额、案件身份、裁判结果标签等字段的详细信息",
        "price": 0.017,
        "totalCalls": 368936,
        "validCalls": 300338,
        "totalCost": 4985.61,
        "supplierApi": "",
        "remark": "",
        "tags": [
            "法律诉讼",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口",
            "风控"
        ]
    },
    {
        "apiCode": "CCCC-0044",
        "apiName1": "企业类型",
        "apiName2": "企业类型查询",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/appreciation/companyType/2.0",
        "description": "可以通过关键字查询企业的类型，具体类型包含普通公司（含“个体工商户”）、香港公司、社会组织、律所、事业单位、基金会",
        "price": 0.017,
        "totalCalls": 325120,
        "validCalls": 319171,
        "totalCost": 5298.24,
        "supplierApi": "",
        "remark": "/services/open/ic/companyType/2.0",
        "tags": [
            "工商信息",
            "天眼查",
            "GET",
            "未改造",
            "低价",
            "常用",
            "Get接口",
            "工商"
        ]
    },
    {
        "apiCode": "CCCC-0020",
        "apiName1": "动产抵押",
        "apiName2": "动产抵押",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/mortgageInfo/2.0",
        "description": "可以通过公司名称或ID获取企业动产抵押公告信息，企业动产抵押公告信息包括被担保债权类型、数额、登记机关等字段信息",
        "price": 0.017,
        "totalCalls": 297430,
        "validCalls": 247040,
        "totalCost": 4100.86,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0015",
        "apiName1": "经营异常",
        "apiName2": "经营异常",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/baseinfo/normal",
        "description": "可以通过公司名称或ID获取企业经营异常信息，经营异常信息包括列入/移除原因、时间、做出决定机关等字段的详细信息",
        "price": 0.017,
        "totalCalls": 232430,
        "validCalls": 181173,
        "totalCost": 3007.47,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0031",
        "apiName1": "企业基本信息",
        "apiName2": "特殊企业基本信息",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/baseinfo/special",
        "description": "可以通过公司名称或ID获取特殊企业基本信息，包含香港公司、社会组织、律所、事业单位、基金会这些特殊企业，不同社会团体所呈现的信息维度不同",
        "price": 0.017,
        "totalCalls": 0,
        "validCalls": 92872,
        "totalCost": 1541.68,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0022",
        "apiName1": "司法拍卖",
        "apiName2": "司法拍卖",
        "apiCategory": "风险识别",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/mr/judicialSale/3.0",
        "description": "可以通过关键字（公司名称、公司id、注册号或社会统一信用代码）获取企业司法拍卖公告信息，企业司法拍卖公告信息包括拍卖公告标题、执行法院、拍卖时间、拍卖标的、起拍价格等字段的详细信息",
        "price": 0.017,
        "totalCalls": 152324,
        "validCalls": 100928,
        "totalCost": 1675.4,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0037",
        "apiName1": "招投标信息",
        "apiName2": "企业招投标信息",
        "apiCategory": "经营信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/m/bids/2.0",
        "description": "可以通过公司名称或ID获取企业招投标信息，招投标信息包括采购人、发布时间、正文信息等字段的详细信息",
        "price": 0.017,
        "totalCalls": 137632,
        "validCalls": 137590,
        "totalCost": 2283.99,
        "supplierApi": "",
        "remark": "/services/open/m/bids/2.0",
        "tags": []
    },
    {
        "apiCode": "CCCC-0129",
        "apiName1": "企业类型",
        "apiName2": "企业类型查询-已方数据源",
        "apiCategory": "工商信息",
        "provider": "自有接口",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/company/model/companyTypeInfo",
        "description": "企业类型查询-已方数据源",
        "price": 0,
        "totalCalls": 37122,
        "validCalls": 37122,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0026",
        "apiName1": "企业股东",
        "apiName2": "企业股东",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/holder/2.0",
        "description": "可以通过公司名称或ID获取企业股东信息，股东信息包括股东名、出资比例、出资金额、股东总数等字段的详细信息",
        "price": 0.017,
        "totalCalls": 36855,
        "validCalls": 36850,
        "totalCost": 611.71,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0133",
        "apiName1": "纳税信用等级与增值税纳税人类型",
        "apiName2": "纳税信用等级与增值税纳税人类型",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/tax/information/rating/taxpayers",
        "description": "可以通过公司名称、注册号或社会统一信用代码，纳税信用等级与增值税纳税人类型",
        "price": 0.017,
        "totalCalls": 29320,
        "validCalls": 29320,
        "totalCost": 486.71,
        "supplierApi": "",
        "remark": "/services/open/m/taxpayer/2.0,services/open/m/taxCredit/2.0",
        "tags": []
    },
    {
        "apiCode": "CCCC-0046",
        "apiName1": "验证企业",
        "apiName2": "验证企业",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/appreciation/verify/match",
        "description": "可以查询公司名称和企业注册号 /组织机构代码 /统一社会信用代码是否对应",
        "price": 0.017,
        "totalCalls": 21077,
        "validCalls": 21077,
        "totalCost": 349.88,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0042",
        "apiName1": "十大股东（十大流通股东）",
        "apiName2": "十大股东（十大流通股东）",
        "apiCategory": "上市信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/stock/shareholder/2.0",
        "description": "可以通过公司名称或ID获取上市公司十大股东和十大流通股东信息，十大股东和十大流通股东信息包括机构或基金、持有数量、持股变化、占股本比例、实际增减持、股份类型等",
        "price": 0.017,
        "totalCalls": 20466,
        "validCalls": 20466,
        "totalCost": 339.74,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0009",
        "apiName1": "股权关系揭示接口",
        "apiName2": "关系族谱-企业投资关系揭示",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/relationship/warning/investment",
        "description": "根据公司名称、关联类型(股权关联、投资关联)、股权比例等参数来揭示公司之间的股权及其投资关系等",
        "price": 1.2,
        "totalCalls": 149447,
        "validCalls": 101532,
        "totalCost": 121838.4,
        "supplierApi": "股权关系揭示接口",
        "remark": "/api/company/findRelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0123",
        "apiName1": "股权关系揭示接口",
        "apiName2": "关系族谱-企业投资关系揭示-PostRequest",
        "apiCategory": "关联族谱",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/qfc/relationship/warning/investment",
        "description": "根据公司名称、关联类型(股权关联、投资关联)、股权比例等参数来揭示公司之间的股权及其投资关系等",
        "price": 1.2,
        "totalCalls": 1094,
        "validCalls": 88,
        "totalCost": 105.6,
        "supplierApi": "股权关系揭示接口",
        "remark": "/api/company/findRelation",
        "tags": []
    },
    {
        "apiCode": "CCCC-0136",
        "apiName1": "是否中交内部企业",
        "apiName2": "是否中交内部企业",
        "apiCategory": "工商信息",
        "provider": "自有接口",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/company/zj/isInternal",
        "description": "是否中交内部企业",
        "price": 0,
        "totalCalls": 203,
        "validCalls": 203,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0131",
        "apiName1": "税务评级",
        "apiName2": "税务评级",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/tax/information/taxCredit",
        "description": "可以通过公司名称或ID获取企业税务评级信息，企业税务评级信息包括评价年度、纳税人信用级别、类型、纳税人识别号、评价单位等字段的详细信息",
        "price": 0.017,
        "totalCalls": 187,
        "validCalls": 186,
        "totalCost": 3.09,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0132",
        "apiName1": "一般纳税人",
        "apiName2": "一般纳税人",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/tax/information/taxpayer",
        "description": "可以通过公司名称或ID获取一般纳税人信息，一般纳税人信息包括纳税人名称、纳税人识别号、纳税人资格类型、主管税务机关、有效期起、有效期止等字段的信息",
        "price": 0.017,
        "totalCalls": 69,
        "validCalls": 69,
        "totalCost": 1.15,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0040",
        "apiName1": "最短路径发现",
        "apiName2": "最短路径发现",
        "apiCategory": "关联族谱",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/rela/shortPath/2.0",
        "description": "可以查询两家公司之间路径最短的关联关系；关系囊括法人、任职、投资、分支、诉讼、竞合、债务，其中法人、任职、投资，不仅有当前现状的关系，还有历史曾经的关系，支持公司之间隐藏关系的深度挖掘",
        "price": 0.017,
        "totalCalls": 68,
        "validCalls": 68,
        "totalCost": 1.13,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0030",
        "apiName1": "企业三要素验证",
        "apiName2": "企业三要素验证",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/verify/2.0",
        "description": "可以通过输入企业名称、法人、注册号 /组织机构代码 /统一社会信用代码，验证三者是否匹配一致",
        "price": 0.017,
        "totalCalls": 66,
        "validCalls": 66,
        "totalCost": 1.1,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0091",
        "apiName1": "招投标动态",
        "apiName2": "招投标动态-分页查询",
        "apiCategory": "经营信息",
        "provider": "自有接口",
        "apiServiceTransform": true,
        "requestMethod": "POST",
        "requestUrl": "/webapi/advanced/tender/bidding/pageList",
        "description": "招投标动态-分页查询",
        "price": 0,
        "totalCalls": 98305,
        "validCalls": 98022,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "企查查接口地址，但实际为落库数据",
        "tags": []
    },
    {
        "apiCode": "CCCC-0060",
        "apiName1": "模糊搜索",
        "apiName2": "青岛交通招商平台-企查查模糊搜索",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/academy/provider/pro/search/searchAutoComplete",
        "description": "青岛交通招商平台-企查查模糊搜索",
        "price": 0.1,
        "totalCalls": 18917,
        "validCalls": 18916,
        "totalCost": 1891.6,
        "supplierApi": "模糊搜索",
        "remark": "https://api.qichacha.com/FuzzySearch/GetList",
        "tags": []
    },
    {
        "apiCode": "CCCC-0076",
        "apiName1": "模糊搜索",
        "apiName2": "西北投项目-企查查模糊搜索",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/northwest/provider/fuzzy/searchAutoComplete",
        "description": "西北投项目-企查查模糊搜索",
        "price": 0.1,
        "totalCalls": 9,
        "validCalls": 9,
        "totalCost": 0.9,
        "supplierApi": "模糊搜索",
        "remark": "https://api.qichacha.com/FuzzySearch/GetList",
        "tags": []
    },
    {
        "apiCode": "CCCC-0078",
        "apiName1": "模糊搜索",
        "apiName2": "企查查批量模糊搜索",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/northwest/provider/regional/batchSearchReason",
        "description": "企业查询海外企业、中国香港企业、中国台湾企业、美股企业暂不支持监控",
        "price": 0.1,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "模糊搜索",
        "remark": "https://api.qichacha.com/FuzzySearch/GetList",
        "tags": []
    },
    {
        "apiCode": "CCCC-0083",
        "apiName1": "模糊搜索",
        "apiName2": "公开接口-企查查模糊搜索",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/depth/relationship/searchAutoComplete",
        "description": "公开接口-企查查模糊搜索",
        "price": 0.1,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "模糊搜索",
        "remark": "https://api.qichacha.com/FuzzySearch/GetList",
        "tags": []
    },
    {
        "apiCode": "CCCC-0120",
        "apiName1": "企业基本信息",
        "apiName2": "企业基本信息",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/commercial/business/getECIComplementInfo",
        "description": "企业基本信息",
        "price": 0,
        "totalCalls": 21,
        "validCalls": 21,
        "totalCost": 0,
        "supplierApi": "企业基本信息",
        "remark": "/yj/ECIComplement/GetInfo",
        "tags": []
    },
    {
        "apiCode": "CCCC-0097",
        "apiName1": "企业详情",
        "apiName2": "青岛交通招商平台-获取企业详情",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/academy/provider/companyDetails/getInfo",
        "description": "云聚·企业工商信息核验API",
        "price": 0,
        "totalCalls": 1669436,
        "validCalls": 1667822,
        "totalCost": 0,
        "supplierApi": "企业详情",
        "remark": "/CustomerECIComplement/GetInfo",
        "tags": []
    },
    {
        "apiCode": "CCCC-0063",
        "apiName1": "企业详情",
        "apiName2": "获取企业详情",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/northwest/provider/company/getInfo",
        "description": "云聚·企业工商信息核验API",
        "price": 0,
        "totalCalls": 9098,
        "validCalls": 9098,
        "totalCost": 0,
        "supplierApi": "企业详情",
        "remark": "/CustomerECIComplement/GetInfo",
        "tags": []
    },
    {
        "apiCode": "CCCC-0074",
        "apiName1": "企业详情",
        "apiName2": "西北投项目-根据统一社会信用代码/企业名称 跳转到企业详情页面",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/northwest/provider/page/companyDetailByCode",
        "description": "西北投项目-根据统一社会信用代码/企业名称 跳转到企业详情页面",
        "price": 0,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "企业详情",
        "remark": "/CustomerECIComplement/GetInfo（模糊搜索，企业详情）",
        "tags": []
    },
    {
        "apiCode": "CCCC-0093",
        "apiName1": "企业详情页面",
        "apiName2": "根据企业名称获取企业详情-页面",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/plugin/supply/companyDetail",
        "description": "向供应链提供,根据企业名称获取企业详情-页面",
        "price": 0.05,
        "totalCalls": 570616,
        "validCalls": 570595,
        "totalCost": 28529.75,
        "supplierApi": "企业详情页面",
        "remark": "/plugin-login/company-gateway（跳转到详情页面）",
        "tags": []
    },
    {
        "apiCode": "CCCC-0085",
        "apiName1": "企业详情页面",
        "apiName2": "企查查详情页面",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/depth/relationship/relationshipMining",
        "description": "进入企查查详情页面",
        "price": 0,
        "totalCalls": 103653,
        "validCalls": 103648,
        "totalCost": 0,
        "supplierApi": "企业详情页面",
        "remark": "/plugin-login（跳转的链接）",
        "tags": []
    },
    {
        "apiCode": "CCCC-0075",
        "apiName1": "企业详情页面",
        "apiName2": "西北投项目-根据keyNo跳转到企查查企业详情-页面",
        "apiCategory": "工商信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/northwest/provider/page/companyDetail",
        "description": "西北投项目-根据keyNo跳转到企查查企业详情-页面",
        "price": 0.05,
        "totalCalls": 3,
        "validCalls": 3,
        "totalCost": 0.15,
        "supplierApi": "企业详情页面",
        "remark": "/plugin-login/companyDetail（跳转到详情页面）",
        "tags": []
    },
    {
        "apiCode": "CCCC-0134",
        "apiName1": "模糊搜索",
        "apiName2": "标准接口-企业模糊查询-全量企业",
        "apiCategory": "工商信息",
        "provider": "大司空",
        "apiServiceTransform": false,
        "requestMethod": "POST",
        "requestUrl": "/webapi/dsk/company/fuzzy/search/all",
        "description": "通过企业id/企业名称/统一社会信用代码，查询该企业的工商基本信息，包括工商地址、登记机关、经营范围、参保人数等",
        "price": 0,
        "totalCalls": 3,
        "validCalls": 3,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0029",
        "apiName1": "企业年报",
        "apiName2": "企业年报",
        "apiCategory": "工商信息",
        "provider": "天眼查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/ic/annualreport/2.0",
        "description": "可以通过公司名称或ID获取企业年报，企业年报包括企业基本信息、股东及出资信息、企业资产状况信息、对外投资信息等字段的详细信息",
        "price": 0.017,
        "totalCalls": 0,
        "validCalls": 0,
        "totalCost": 0,
        "supplierApi": "",
        "remark": "",
        "tags": []
    },
    {
        "apiCode": "CCCC-0090",
        "apiName1": "招投标信息",
        "apiName2": "开放接口-招投标信息详情",
        "apiCategory": "经营信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/advanced/tender/getDetail",
        "description": "开放接口-招投标信息详情",
        "price": 1,
        "totalCalls": 48,
        "validCalls": 48,
        "totalCost": 48,
        "supplierApi": "招投标信息",
        "remark": "/yj/TenderCheck/GetDetail",
        "tags": []
    },
    {
        "apiCode": "CCCC-0092",
        "apiName1": "招投标信息",
        "apiName2": "开放接口-招投标信息高级查询",
        "apiCategory": "经营信息",
        "provider": "企查查",
        "apiServiceTransform": false,
        "requestMethod": "GET",
        "requestUrl": "/webapi/advanced/tender/search",
        "description": "开放接口-招投标信息高级查询",
        "price": 1,
        "totalCalls": 48,
        "validCalls": 48,
        "totalCost": 48,
        "supplierApi": "招投标信息",
        "remark": "/yj/TenderCheck/GetList",
        "tags": []
    }
]

export default data